services:
  - type: worker
    name: kemri-automation
    runtime: python
    buildCommand: pip install -r Python/req.txt
    startCommand: python Python/export.py
    branch: Automation
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
